/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type DiscordClient = Client
export class Client {
  clientId: string
  constructor(clientId: string)
  connect(): Promise<void>
}
