/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type DiscordClient = Client
export class Client {
  clientId: string
  constructor(clientId: string)
  get user(): DiscordUser | null
  connect(): Promise<void>
}
export type DiscordUser = User
export class User {
  constructor()
  get username(): string
  get discriminator(): number
  get id(): string
}
